
test_name: "TAL_allmaps_shared"

architecture: "fast"
n_scans: 2
train_mode: "Std"
test_mode: "Std"

start_n: 0
n: 1
set_n: 1

random_seed: 10000

n_train_steps: 120000
n_test_laps: 20

noise_std: 0.0
max_speed: 8
reward: "TAL"

# Use a single shared actor across all maps/runs
shared_actor_name: "TAL_shared"

runs:
  - map_name: "f1_aut"
  - map_name: "f1_aut_wide"
  - map_name: "f1_esp"
  - map_name: "f1_mco"
  - map_name: "f1_gbr"
