
test_name: "TAL_allmaps"

architecture: "fast"
n_scans: 2
train_mode: "Std"
test_mode: "Std"

start_n: 0           # starting repetition index
n: 1                 # number of repetitions (seeds)
set_n: 1             # used in run name to track seed count

random_seed: 10000

n_train_steps: 120000
n_test_laps: 20

noise_std: 0.0
max_speed: 8
reward: "TAL"

runs:
  - map_name: "f1_aut"
  - map_name: "f1_aut_wide"
  - map_name: "f1_esp"
  - map_name: "f1_mco"
  - map_name: "f1_gbr"
